import { Dimensions, StyleSheet } from 'react-native';
import { Fonts } from '../../common/fonts';
import { normalize } from "../../common/normalize";
const width = Dimensions.get('window').width;
const height = Dimensions.get('window').height;

export const styles = StyleSheet.create({
  scrlView_container: {
    flexGrow: 1,
  },
  main_container: {
    flex: 1,
  },
  header_container_style: {
    backgroundColor: 'transparent',
    position: 'absolute',
    zIndex: 100,
    top: 0,
    left: 0,
    right: 0,
    elevation: 0,
    shadowOpacity: 0,
    borderBottomWidth: 0,
    marginTop: 10,
  },
  header_user_img_style: {
    width: 24,
    height: 24,
    borderRadius: 24 / 2,
    backgroundColor: '#ddd',
    marginLeft: 16,
    marginVertical: 12,
  },
  img_bg_style: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  artist_img_viewer: {
    paddingHorizontal: 20,
    marginLeft: 5,
    marginTop: 68,
    width: '100%',
    height: 435,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  artist_following_details_container: {
    flexDirection: 'row',
    backgroundColor: '#000000',
    marginHorizontal: 16,
    borderRadius: 10,
  },
  gigs_enjoy_count_num_view: {
    flex: 1,
  },
  box_title_view: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  following_details_title_text: {
    fontFamily: Fonts.OpenSans_regular,
    fontSize: normalize(12),
    color: '#dddddd',
    marginTop: 25,
  },
  box_following_count_view: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  following_details_count_text: {
    fontFamily: Fonts.OpenSans_semibold,
    fontSize: normalize(24),
    color: '#dddddd',
    marginTop: 5,
    marginBottom: 30,
  },
  location_n_details_view: {
    marginTop: 24,
    marginHorizontal: 16,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    alignSelf: 'flex-start',
    width: '100%',
  },
  location_n_social_icon_view: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  location_text_style: {
    fontFamily: Fonts.OpenSans_regular,
    fontSize: normalize(16),
    color: '#dddddd',
  },
  social_btn_view: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#252628',
    borderRadius: 5,
    marginRight: 8,
  },
  social_icon_style: {
    marginVertical: 12,
    marginHorizontal: 13,
  },
  artist_bio_text_view: {
    marginTop: 23,
    marginVertical: 16,
  },
  artist_bio_text_style: {
    fontFamily: Fonts.OpenSans_regular,
    fontSize: normalize(14),
    color: '#fff',
  },
  Your_Mutuals_text_style: {
    fontFamily: Fonts.OpenSans_semibold,
    fontSize: normalize(16),
    color: '#dddddd',
    alignSelf: 'flex-start',
    marginBottom: 16,
    marginLeft: 16,
  },
  mutual_friend_view: {
    backgroundColor: '#0c0c0c',
    width: '100%',
    borderRadius: 10,
  },
  mutual_friend_text_count: {
    fontFamily: Fonts.OpenSans_semibold,
    fontSize: normalize(16),
    color: '#dddddd',
    margin: 16,
  },
  similar_artist_img__style: {
    width: 100,
    height: 100,
    borderRadius: 100 / 2,
    borderWidth: 1,
    borderColor: '#fff',
  },
  similar_artist_name_text__style: {
    color: '#dddddd',
    fontFamily: Fonts.OpenSans_semibold,
    fontSize: normalize(10),
    marginTop: 10,
    marginBottom: 47,
  },
  similar_artist_box_view__style: {
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 17,
    marginVertical: 8,
  },
  tab_view_title: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  tab_view_count: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  title_text_tab: {
    color: '#777777',
    fontFamily: Fonts.OpenSans_regular,
    fontSize: normalize(14),
    marginLeft: 16,
    marginVertical: 14,
  },
  count_text_tab: {
    color: '#777777',
    fontFamily: Fonts.OpenSans_regular,
    fontSize: normalize(32),
    marginRight: 16,
    marginVertical: 14,
  },
  genres_text_tab: {
    color: '#777777',
    fontFamily: Fonts.OpenSans_regular,
    fontSize: normalize(12),
    marginVertical: 12,
  },
  Badges_earned_view: {
    marginTop: 24,
    marginLeft: 16,
    borderTopLeftRadius: 15,
    borderBottomLeftRadius: 15,
    backgroundColor: '#27282a',
    width: '100%',
  },
  Badges_Earned_text_style: {
    color: '#fff',
    fontFamily: Fonts.OpenSans_semibold,
    fontSize: normalize(16),
    marginTop: 20,
    marginLeft: 20,
  },
  budge_icon_container: {
    flexDirection: 'row',
  },
  unlimited_fan_badge_view: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badge_img_style: {
    marginTop: 5,
    marginBottom: 21,
  },
  //
  rachel_view: {
    backgroundColor: '#000',
    width: '100%',
  },
  rachel_title_view: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rachel_text_style: {
    color: '#ddd',
    fontFamily: Fonts.OpenSans_semibold,
    fontSize: normalize(18),
    marginLeft: 16,
  },
  see_all_text_style: {
    color: '#ddd',
    fontFamily: Fonts.OpenSans_semibold,
    fontSize: normalize(12),
    marginRight: 16,
  },
  rachel_Row_view: {
    flexDirection: 'row',
    marginTop: 19,
    marginBottom: 36,
    marginLeft: 16,
  },
  rachel_view_btn: {
    width: 152,
    height: 220,
    backgroundColor: '#252628',
    borderRadius: 8,
    marginRight: 10,
  },
  Artist_name_text: {
    color: '#ddd',
    fontFamily: Fonts.OpenSans_semibold,
    fontSize: normalize(24),
  },
  follow_pop_up_btn: {
    borderRadius: 10,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    width: '40%',
    marginTop: 16,
    flexDirection: 'row',
  },
  follow_btn_text: {
    color: '#1b1c20',
    fontFamily: Fonts.OpenSans_semibold,
    fontSize: normalize(14),
    marginVertical: 10,
  },
  medal_img_style: {
    resizeMode: 'contain',
    height: '20%',
    width: '20%',
    marginRight: 20,
  },
  event_artist_img__style: {
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  artist_name_event_attend_text_screen: {
    color: '#ddd',
    fontFamily: Fonts.OpenSans_regular,
    fontSize: normalize(12),
    marginTop: 111,
  },
  event_name_event_attend_text_screen: {
    color: '#ddd',
    fontFamily: Fonts.PlayfairDisplay_Black,
    fontSize: normalize(18),
    marginTop: 5,
    marginBottom: 22,
    marginHorizontal: 24,
  },
  inside_img_event_attend: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  empty_tab_view: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  blank_view_white_empty: {
    marginTop: 16,
    width: 100,
    height: 67,
    borderRadius: 10,
    backgroundColor: '#686868',
  },
  empty_view_text_style: {
    color: '#777',
    fontFamily: Fonts.OpenSans_regular,
    fontSize: normalize(12),
    textAlign: 'center',
    marginHorizontal: 13,
    marginTop: 16,
    marginBottom: 28,
  },
  follow_pop_option_btn: {
    borderRadius: 10,
    backgroundColor: '#252628',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: '40%',
  },
  follow_btn_option_text: {
    color: '#525354',
    fontFamily: Fonts.OpenSans_semibold,
    fontSize: normalize(14),
    marginVertical: 10,
    marginLeft: 16,
  },
  genre_artist:{
    width: '100%',
    borderRadius: 10,
    flexDirection: 'row',
    overflow: 'hidden',
  }
});
